variables:
  GIT_STRATEGY: clone

stages:
  - build
  - test
  - deploy

.virtenv: &virtualenv
  - source /work/voss_ar/Software/miniconda3/etc/profile.d/conda.sh
  - conda activate
  # To make things faster, re-use existing site packages. 
  - python -m venv virtualenv --system-site-packages
  - source virtualenv/bin/activate
  # Python's venv comes with an older version of pip, so update it.
  - pip install --upgrade pip
  # Check python version
  - which python
  - which pytest
  # Set-up MPI
  - export PATH=/work/voss_ar/Software/mpich-3.4.2/bin:$PATH
  - export LD_LIBRARY_PATH=/work/voss_ar/Software/mpich-3.4.2/lib
  - which mpiexec
  # Check location
  - pwd
  
build:
  # This stage only tests if the installation is possible.
  # The evironment created herein will be discared and re-created in the test stage.
  stage: build
  tags:
    - lk
  script:
    - *virtualenv
    - pip install -e .
    # Check result of installation
    - which loads-kernel
    - which model-viewer
    - which loads-compare 

test:
  stage: test
  timeout: 3 hours
  coverage: '/^TOTAL.+?(\d+\%)$/'
  tags:
    - lk
  dependencies:
    - build
  script:
    # Set-up the environement
    - *virtualenv
    # Install with -e (in editable mode) to allow the tracking of the test coverage
    - pip install -e .
    - which loads-kernel
    # Get the examples repository
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.dlr.de/loads-kernel/loads-kernel-examples.git
    # Assemble the tutorials to a jupyter book and build htlm pages
    - jupyter-book build tutorials
    # Run the actual testing of the code with pytest
    - pytest -v --basetemp=./test_tmp --cov=loadskernel  --cov=modelviewer --cov=loadscompare --junitxml=testresult.xml
    # Create some reports
    - coverage report
    - coverage xml -o coverage.xml
    - coverage html --directory ./coverage
  artifacts:
    when: always
    paths:
      - coverage.xml
      - testresult.xml
      - coverage
      - tutorials
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: testresult.xml

pages:
  stage: deploy
  tags:
    - lk
  dependencies:
    - test
  script:
    - mkdir public
    # Publish the coverage htlm results
    - mv coverage public/coverage
    # Publish the htlm tutorials
    - mv tutorials/_build/html public/tutorials
  artifacts:
    paths:
      - public
