variables:
  GIT_STRATEGY: clone

stages:
  - test
  - deploy


test:
  stage: test
  tags:
    - lk
  script:
  	- set +e  # switch off break on error
  	- source /opt/AE/share/python/switching/py_env.sh anaconda3
  	- set -e  # switch on break on error
 	- which python
  	- which pytest
  	- mkdir ./test_tmp
    - pytest -v --basetemp=./test_tmp --cov-report xml:coverage.xml --cov=loadskernel --junitxml=testresult.xml
    - coverage xml -o coverage.xml
    - coverage report
    - coverage html
  artifacts:
    when: always
    paths:
      - coverage.xml
      - testresult.xml
      - htmlcov/
    reports:
      cobertura: coverage.xml
      junit: testresult.xml

pages:
  stage: deploy
  tags:
    - lk
  dependencies:
    - test
  script:
    - mv htmlcov/ public/coverage
  artifacts:
    paths:
      - public