variables:
  GIT_STRATEGY: clone

stages:
  - test

before_script:
  - mkdir ./test_tmp
  - set +e  # switch off break on error
  - source /opt/AE/share/python/switching/py_env.sh anaconda3
  - set -e  # switch on break on error
  - which python
  - which pytest

test:
  stage: test
  tags:
    - lk
  script:
    - pytest -v --basetemp=./test_tmp --cov-report xml:coverage.xml --cov=loadskernel --junitxml=testresult.xml
    - coverage xml -o coverage.xml
    - coverage report
  artifacts:
    when: always
    paths:
      - coverage.xml
      - testresult.xml
    reports:
      cobertura: coverage.xml
      junit: testresult.xml
