variables:
  GIT_STRATEGY: clone

stages:
  - test
  - deploy


test:
  stage: test
  timeout: 3 hours
  coverage: '/^TOTAL.+?(\d+\%)$/'
  tags:
    - lk
  script:
    - set +e  # switch off break on error
    - source /opt_ae/anaconda/miniconda-4.10_py3.8/etc/profile.d/conda.sh
    - conda activate myminiconda
    - set -e  # switch on break on error
    - which python
    - which pytest

    - pytest -v --basetemp=./test_tmp --cov-report xml:coverage.xml --cov=loadskernel --junitxml=testresult.xml
    - coverage xml -o coverage.xml
    - coverage report
    - coverage html --directory ./coverage
  artifacts:
    when: always
    paths:
      - coverage.xml
      - testresult.xml
      - coverage/
    reports:
      cobertura: coverage.xml
      junit: testresult.xml

pages:
  stage: deploy
  tags:
    - lk
  dependencies:
    - test
  script:
    - mkdir public
    - mv coverage public/coverage
  artifacts:
    paths:
      - public
