# This workflow will try to build and install the software in different ways.

name: Build and installation tests

# Restrict permissions at top-level to 'read' as a minimal explicit permission.
permissions:
  contents: read

on:
  push:
    branches: ['master', 'devel']
  pull_request:
    branches: '*'
  schedule:
    - cron: '0 2 * * 0'

jobs:
  pure-pip-installation:
    # This stage only tests if the installation is possible.
    # The evironment created herein will be discared and re-created in the test stage.
    runs-on: ubuntu-latest
    strategy:
      matrix:
      # Add multiple Python versions here to run tests on new(er) versions.
        python-version: ["3.12", "3.13"]
      fail-fast: false
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build and install
      run: |
        python -m pip install --upgrade pip
        # Install with -e (in editable mode) to allow the tracking of the test coverage
        pip install -e .
        # Check result of installation
        python -c "import loadskernel"
        which loads-kernel
        which model-viewer
        which loads-compare

  conda-and-pip-installation:
    # This stage only tests if the installation is possible.
    # The evironment created herein will be discared and re-created in the test stage.
    runs-on: ubuntu-latest
    strategy:
      matrix:
      # Add multiple Python versions here to run tests on new(er) versions.
        python-version: ["3.12", "3.13"]
      fail-fast: false
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup headless display
      uses: pyvista/setup-headless-display-action@v3
    - name: Build and install
      run: |
        # Install same requirements as to be used during regression testing
        source $CONDA/etc/profile.d/conda.sh
        conda create -n my_env python=${{ matrix.python-version }}
        conda activate my_env
        conda install -y -q -c conda-forge --file ./tests/list_of_packages.txt || true
        # Install with -e (in editable mode) to allow the tracking of the test coverage
        pip install -e .[extras,test]
        # Check result of installation
        python -c "import loadskernel"
        python -c "import loadscompare"
        python -c "import modelviewer"
        which loads-kernel
        which model-viewer
        which loads-compare
  